


# my_file = open("people1.txt")
# file_data = my_file.read()
# print (file_data)
# my_file.close(z) 




# def twopowers(number):
#     if number==1:
#         return 1
#     return 2 * twopowers(number-1)

# index=1
# while(index<10):
#     print(twopowers(index))
#     index+=1 





# a=open("people1-exercise.txt","w")
# a.write("rishabh - meerut\nmtiyaz - delhi\nrishabh - meerut\nimtiyaz - delhi\nnilima - cochin\nrati - shimla\nayishah - delhi\nraghu - shimla\nnaseer - kanpur\narthikeyan - delhi\nsalma - jaipur\nbrijesh - delhi\ngovind - delhi\npuneet - shimla\nsiddhi - delhi\nsuman - jaipur\nrajeev - shimla\nmohinder - delhi\nrajendra - jaipur\npriyanka - shimla\nneela - delhi\nsashi - jaipur\nsarika - delhi\ndeepti - shimla\nharshad - delhi\ntrishna - raipur\npradeep - jaipur\nsekhar - delhi\nnand - delhi\n anoop - delhi\nbalwinder - toyko\n")
# a.close()
 
